#demo
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'Junit'
    displayName: 'Junit stage'
    jobs:
      - job: 'JunitTest'
        displayName: 'Running unit test'
        steps:
          - script: echo 'test9962061144'
          - task: Maven@1
            inputs:
              mavenPomFile: 'pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: true
              sonarQubeRunAnalysis: false